name: Instagram Scraper to Firestore + Blog Files

on:
  schedule:
    - cron: "*/240 * * * *"  # roda a cada 4 horas
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r ./.github/workflows/requirements.txt

      - name: Run main.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > serviceAccountKey.json
          python .github/workflows/main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit changes
        run: |
          git add src/data/blog public/assets/contents/blog
          git diff --cached --quiet || git commit -m "Atualiza posts do Instagram e blog [skip ci]"
          git push origin HEAD